services:
  app:
    build:
      context: .
      args:
        PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
    ports:
      - '4321:4321'
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
